# Generated by go2rpm 1.6.0
%bcond_without check
%global debug_package %{nil}

# https://github.com/jdxcode/netrc
%global goipath         github.com/jdxcode/netrc
%global commit          926c7f70242abe00179235c2b06bb647c0c53a12

%gometa

%global common_description %{expand:
Golang netrc parser.}

%global golicenses      LICENSE
%global godocs          examples README.md

Name:           %{goname}
Version:        0
Release:        0.1%{?dist}
Summary:        Golang netrc parser

License:        MIT
URL:            %{gourl}
Source0:        %{gosource}

BuildRequires: golang(gopkg.in/check.v1)

%description
%{common_description}

%gopkg

%prep
%goprep

%install
%gopkginstall

%if %{with check}
%check
%gocheck
%endif

%gopkgfiles

%changelog
* Wed Jun 01 2022 Brandon Bennett <brandon@brbe.me> - 0-0.1.20220601git926c7f7
- Initial package
