# Generated by go2rpm 1.6.0
%bcond_without check
%global debug_package %{nil}

# https://github.com/jhump/protocompile
%global goipath         github.com/jhump/protocompile
%global commit          d705409f108f87b9aad4f915132a7b3f4cb37ccb

%gometa

%global common_description %{expand:
A parsing/linking engine for protobuf; the guts for a pure Go replacement of
protoc.}

%global golicenses      LICENSE
%global godocs          README.md grammar/README.md sourceinfo/test-source-\\\
                        info.txt

Name:           %{goname}
Version:        0
Release:        0.1%{?dist}
Summary:        A parsing/linking engine for protobuf; the guts for a pure Go replacement of protoc

# Upstream license specification: Apache-2.0
License:        ASL 2.0
URL:            %{gourl}
Source0:        %{gosource}

%description
%{common_description}

%gopkg

%prep
%goprep

%generate_buildrequires
%go_generate_buildrequires

%install
%gopkginstall

%if %{with check}
%check
%gocheck
%endif

%gopkgfiles

%changelog
* Wed Jun 01 2022 Brandon Bennett <brandon@brbe.me> - 0-0.1.20220601gitd705409
- Initial package
