# Generated by go2rpm 1.6.0
%bcond_without check
%global debug_package %{nil}

# https://github.com/ejoffe/profiletimer
%global goipath         github.com/ejoffe/profiletimer
Version:                0.2.0

%gometa

%global common_description %{expand:
A simple utility tool to profile go code.}

%global golicenses      LICENSE
%global godocs          readme.md

Name:           %{goname}
Release:        1%{?dist}
Summary:        A simple utility tool to profile go code

License:        MIT
URL:            %{gourl}
Source0:        %{gosource}

%description
%{common_description}

%gopkg

%prep
%goprep

%generate_buildrequires
%go_generate_buildrequires

%install
%gopkginstall

%if %{with check}
%check
%gocheck
%endif

%gopkgfiles

%changelog
* Wed Jun 22 2022 Brandon Bennett <brandon@brbe.me> - 0.2.0-1
- Initial package
